name: CI

on:
  push:
    branches: ["development", "main"]
  pull_request:
    types: [opened, synchronize]
    branches:
      - development
      - main

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  testApp:
    name: Test App
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
        working-directory: ./app

      - name: Create env
        run: cp .env.example .env
        working-directory: ./app

      - name: Start SvelteKit Server
        run: npm run dev &
        working-directory: ./app

      - name: Run cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: true
          project: ./app
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Stop SvelteKit Server
        run: pkill -f "sirv" || true

  testHTMLGenerator:
    name: Test HTML Generator
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Run cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: true
          project: ./doc/reference-course
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.HTML_CYPRESS_RECORD_KEY }}
